// Mocks generated by Mockito 5.4.6 from annotations
// in brick_manual/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:brick_manual/instruction_metadata.dart' as _i4;
import 'package:brick_manual/lego_set_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LegoSetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLegoSetRepository extends _i1.Mock implements _i2.LegoSetRepository {
  MockLegoSetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> fetchManifest() =>
      (super.noSuchMethod(
            Invocation.method(#fetchManifest, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i4.InstructionMetadata>> fetchIndexFile({
    required String? indexUrl,
    void Function(int, int)? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchIndexFile, [], {
              #indexUrl: indexUrl,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i3.Future<List<_i4.InstructionMetadata>>.value(
              <_i4.InstructionMetadata>[],
            ),
          )
          as _i3.Future<List<_i4.InstructionMetadata>>);
}
