"""Rule definitions for rule-based classifiers."""

from build_a_long.pdf_extract.classifier.rules.base import (
    Filter,
    IsInstanceFilter,
    MaxScoreRule,
    Rule,
    RuleContext,
)
from build_a_long.pdf_extract.classifier.rules.geometry import (
    AspectRatioRule,
    CornerDistanceScore,
    CoverageRule,
    EdgeProximityRule,
    InBottomBandFilter,
    IsHorizontalDividerRule,
    IsVerticalDividerRule,
    SizeRangeRule,
    SizeRatioRule,
    TextContainerFitRule,
    TopLeftPositionScore,
)
from build_a_long.pdf_extract.classifier.rules.text import (
    BagNumberFontSizeRule,
    BagNumberTextRule,
    FontSizeMatch,
    FontSizeRangeRule,
    FontSizeSmallerThanRule,
    PageNumberTextRule,
    PageNumberValueMatch,
    PartCountTextRule,
    PartNumberTextRule,
    PieceLengthValueRule,
    RegexMatch,
    StepNumberTextRule,
    StepValueMaxFilter,
)
from build_a_long.pdf_extract.classifier.rules.visual import (
    CurveCountRule,
    StrokeColorScore,
)

__all__ = [
    "AspectRatioRule",
    "BagNumberFontSizeRule",
    "BagNumberTextRule",
    "CornerDistanceScore",
    "CoverageRule",
    "CurveCountRule",
    "EdgeProximityRule",
    "Filter",
    "FontSizeMatch",
    "FontSizeRangeRule",
    "FontSizeSmallerThanRule",
    "InBottomBandFilter",
    "IsHorizontalDividerRule",
    "IsInstanceFilter",
    "IsVerticalDividerRule",
    "MaxScoreRule",
    "PageNumberTextRule",
    "PageNumberValueMatch",
    "PartCountTextRule",
    "PartNumberTextRule",
    "PieceLengthValueRule",
    "RegexMatch",
    "Rule",
    "RuleContext",
    "SizeRangeRule",
    "SizeRatioRule",
    "StepNumberTextRule",
    "StepValueMaxFilter",
    "StrokeColorScore",
    "TextContainerFitRule",
    "TopLeftPositionScore",
]
