pex_binary(
    name="analyze_deletions",
    entry_point="analyze_deletions.py",
    dependencies=[
        "src/build_a_long/pdf_extract/extractor",
        "src/build_a_long/pdf_extract/classifier",
    ],
)
